#!/usr/bin/env python3
"""
First-run helper: prompts for autorouter.aero credentials and writes config.py.
Called automatically by start_notam_linux.sh when config.py is absent.
"""
import base64
import getpass
import os

CONFIG_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'config.py')
PORT        = 8766

TEMPLATE = '''\
import base64

# ── Server ────────────────────────────────────────────────────────────────────
PORT: int = {port}

# ── autorouter.aero credentials ───────────────────────────────────────────────
# Generated by setup_config.py — do not share this file.
EMAIL:    str = base64.b64decode({email_b64}).decode()
PASSWORD: str = base64.b64decode({pass_b64}).decode()

# ── GitHub sync (optional — for cross-device snapshot sync) ───────────────────
# Create a private repository, then a Personal Access Token with repo scope.
# Leave blank to disable sync and keep snapshots local only.
GITHUB_REPO:   str = ''   # e.g. 'username/notam-snapshots'
GITHUB_TOKEN:  str = ''   # e.g. 'github_pat_xxxxxxxxxxxxxxxxxxxx'
GITHUB_BRANCH: str = 'main'

# ── Anthropic API key (optional — for AI NOTAM summaries) ─────────────────────
# Get a key at https://console.anthropic.com — cost ~$0.003 per full briefing.
ANTHROPIC_API_KEY: str = ''

# ── openAIP API key (optional — for AZBA zone refresh and aviation tile layer) ─
# Get a key at https://www.openaip.net (free account, API Clients section).
OPENAIP_API_KEY: str = ''

# ── AUGUR RAIM API credentials (optional — for GNSS RAIM outage predictions) ──
# Request a free account at: https://augur.eurocontrol.int/connectivity/
AUGUR_USERNAME: str = ''
AUGUR_PASSWORD: str = ''
'''

def _encode(value: str) -> str:
    return repr(base64.b64encode(value.encode('utf-8')))

def main():
    print()
    print('  ── NOTAM Briefing: first-run setup ─────────────────────────────────')
    print('  Credentials are stored obfuscated in config.py (never share that file).')
    print()
    email    = input('  autorouter.aero email:    ').strip()
    password = getpass.getpass('  autorouter.aero password: ').strip()
    if not email or not password:
        print('  ERROR: email and password are required.')
        raise SystemExit(1)
    with open(CONFIG_PATH, 'w') as f:
        f.write(TEMPLATE.format(
            port      = PORT,
            email_b64 = _encode(email),
            pass_b64  = _encode(password),
        ))
    print(f'  config.py written ✓')
    print()

if __name__ == '__main__':
    main()
